//Layout
import Layout from '@/app/(site)/components/global/Layout'

//CSS
import './globals.css'

//Fonts
import { Poppins } from 'next/font/google'
const poppins = Poppins({ subsets: ['devanagari'], weight: ['200', '600', '900'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
